[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Henrik Melsom <>"]
edition = "2021"
publish = false

[dependencies]
regex = "1"
glam = "0.22"
rayon = "1.6"
petgraph = "0.6"
crossterm = "0.25"
